
export const CHANGE_CALENDAR_MODE = "CHANGE_CALENDAR_MODE";

export const MOVE_TO_PREV_DATE = "MOVE_TO_PREV_DATE";
export const MOVE_TO_NEXT_DATE = "MOVE_TO_NEXT_DATE";

export const ADD_NEW_EVENT = "ADD_NEW_EVENT";
