export const CHANGE_CALENDAR_MODE = "CHANGE_CALENDAR_MODE";

export const MOVE_TO_PREV_DATE = "MOVE_TO_PREV_DATE";
export const MOVE_TO_NEXT_DATE = "MOVE_TO_NEXT_DATE";
export const MOVE_TO_TODAY = "MOVE_TO_TODAY";

export const ADD_NEW_EVENT = "ADD_NEW_EVENT";
export const GET_USER_EVENTS = "GET_USER_EVENTS";
export const UPDATE_USER_EVENT = "UPDATE_USER_EVENT";
export const DELETE_USER_EVENT = "DELETE_USER_EVENT";
