export const GET_STORED_EVENTS_DATA = "GET_STORED_EVENTS_DATA";
export const ADD_EVENT = "ADD_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

export const CLICK_PREV_DATE_BUTTON = "CLICK_PREV_DATE_BUTTON";
export const CLICK_NEXT_DATE_BUTTON = "CLICK_NEXT_DATE_BUTTON";
export const CHANGE_VIEW_TYPE = "CHANGE_VIEW_TYPE";
export const SHOW_ERROR_MESSAGE = "SHOW_ERROR_MESSAGE";
