export const ADD_EVENT = "ADD_EVENT";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const CLICK_PREV_BUTTON = "CLICK_PREV_BUTTON"; // CLICK PREV DATE BUTTON - 변경
export const CLICK_NEXT_BUTTON = "CLICK_NEXT_BUTTON";
export const CHANGE_WEEKLY_VIEW = "CHANGE_WEEKLY_VIEW";
export const GET_EVENTS_DATA = "GET_EVENTS_DATA";
export const UPDATE_EVENT = "UPDATE_EVENT";
