export const UPDATE_EVENT_FORM = "UPDATE_EVENT_FORM";

export const UPDATE_USER_EVENT = "UPDATE_USER_EVENT";
export const DELETE_USER_EVENT = "DELETE_USER_EVENT";

export const UPDATE_CURRENT_DATE = "UPDATE_CURRENT_DATE";
