 export const eventForm = {
   SET_YEAR: "SET_YEAR",
   SET_MONTH: "SET_MONTH",
   SET_DATE: "SET_DATE",
   SET_FROM_HOUR: "SET_FROM_HOUR",
   SET_TO_HOUR: "SET_TO_HOUR",
   SET_ALL_DATE: "SET_ALL_DATE",
   SET_TITLE: "SET_TITLE",
   SET_CONTENT: "SET_CONTENT",
   SET_EVENT: "SET_EVENT",
   CORRECT_EVENT: "CORRECT_EVENT",
   CLEAR_FORM: "CLEAR_FORM",
 };

 export const userEvent = {
   SET_EVENT: "SET_EVENT",
   SET_EVENT_ALL: "SET_EVENT_ALL",
   DELETE_EVENT: "DELETE_EVENT",
 };

 export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
