/*

  Action Types

  ref: https://github.com/reduxjs/redux/blob/master/examples/shopping-cart/src/constants/ActionTypes.js

 */
export const ACTION = {
  SHOW_MONTHLY: "SHOW_MONTHLY",
  SHOW_NEXT_MONTH: "SHOW_NEXT_MONTH",
  SHOW_PREVIOUS_MONTH: "SHOW_PREVIOUS_MONTH",

  SHOW_WEEKLY: "SHOW_WEEKLY",
  SHOW_NEXT_WEEK: "SHOW_NEXT_WEEK",
  SHOW_PREVIOUS_WEEK: "SHOW_PREVIOUS_WEEK",

  SHOW_DAILY: "SHOW_WEEKLY",
  SHOW_NEXT_DAY: "SHOW_NEXT_DAY",
  SHOW_PREVIOUS_DAY: "SHOW_PREVIOUS_DAY",

  ADD_EVENT: "ADD_EVENT",
  DELETE_EVENT: "DELETE_EVENT",
  EDIT_EVENT_TITLE: "EDIT_EVENT_TITLE",
  EDIT_EVENT_DESCRIPTION: "EDIT_EVENT_DESCRIPTION",
  EDIT_EVENT_DATE: "EDIT_EVENT_DATE",
  EDIT_EVENT_START_TIME: "EDIT_EVENT_START_TIME",
  EDIT_EVENT_END_TIME: "EDIT_EVENT_END_TIME",
};
