export const FIREBASE_API_KEY = process.env.REACT_APP_SECRET_KEY;
export const FIREBASE_AUTHDOMAIN = process.env.REACT_APP_AUTHDOMAIN;
export const FIREBASE_DATABASEURL = process.env.REACT_APP_DATABASEURL;
export const FIREBASE_PROJECTID = process.env.REACT_APP_PROJECTID;
export const FIREBASE_STORAGEBUCKET = process.env.REACT_APP_STORAGEBUCKET;
export const FIREBASE_MESSAGINGSENDERID = process.env.REACT_APP_MESSAGINGSENDERID;
export const FIREBASE_APPID = process.env.REACT_APP_APPID;