import moment from "moment";

export const mockEvent = [
  {
    id: "eventID111",
    title: "read book",
    description: "read book so long long time",
    date: moment().add(-1, "days").format("YYYY-MM-DD"),
    startTime: 10,
    endTime: 19,
  },
  {
    id: "eventID222",
    title: "coding",
    description: "do or die",
    date: moment().add(0, "days").format("YYYY-MM-DD"),
    startTime: 2,
    endTime: 5,
  },
  {
    id: "eventID333",
    title: "play boardgame",
    description: "win or die",
    date: moment().add(1, "days").format("YYYY-MM-DD"),
    startTime: 5,
    endTime: 9,
  },
  {
    id: "eventID444",
    title: "read book",
    description: "read book so long long time",
    date: moment().add(2, "days").format("YYYY-MM-DD"),
    startTime: 10,
    endTime: 19,
  },
  {
    id: "eventID555",
    title: "coding",
    description: "do or die",
    date: moment().add(3, "days").format("YYYY-MM-DD"),
    startTime: 2,
    endTime: 5,
  },
  {
    id: "eventID666",
    title: "play boardgame",
    description: "win or die",
    date: moment().add(4, "days").format("YYYY-MM-DD"),
    startTime: 5,
    endTime: 9,
  },
  {
    id: "eventID777",
    title: "read book",
    description: "read book so long long time",
    date: moment().add(5, "days").format("YYYY-MM-DD"),
    startTime: 10,
    endTime: 19,
  },
  {
    id: "eventID888",
    title: "coding",
    description: "do or die",
    date: moment().add(6, "days").format("YYYY-MM-DD"),
    startTime: 2,
    endTime: 5,
  },
  {
    id: "eventID999",
    title: "play boardgame",
    description: "win or die",
    date: moment().add(7, "days").format("YYYY-MM-DD"),
    startTime: 5,
    endTime: 9,
  },
  {
    id: "eventID101010",
    title: "read book",
    description: "read book so long long time",
    date: moment().add(15, "days").format("YYYY-MM-DD"),
    startTime: 10,
    endTime: 19,
  },
  {
    id: "eventID111111",
    title: "coding",
    description: "do or die",
    date: moment().add(27, "days").format("YYYY-MM-DD"),
    startTime: 2,
    endTime: 5,
  },
  {
    id: "eventID121212",
    title: "play boardgame",
    description: "win or die",
    date: moment().add(47, "days").format("YYYY-MM-DD"),
    startTime: 5,
    endTime: 9,
  },
  {
    id: "eventID131313",
    title: "read book",
    description: "read book so long long time",
    date: moment().add(-116, "days").format("YYYY-MM-DD"),
    startTime: 10,
    endTime: 19,
  },
  {
    id: "eventID141414",
    title: "coding",
    description: "do or die",
    date: moment().add(-253, "days").format("YYYY-MM-DD"),
    startTime: 2,
    endTime: 5,
  },
  {
    id: "eventID151515",
    title: "play boardgame",
    description: "win or die",
    date: moment().add(189, "days").format("YYYY-MM-DD"),
    startTime: 5,
    endTime: 9,
  },
];
